#!/usr/bin/env php
<?php

require_once __DIR__.'/AlboradaKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new AlboradaKernel('dev', true);

$application = new Application($kernel);
$application->run();
